-- Insert sample quotes for Ahnaf (user_id: 01928952-694d-7ac4-b454-ad9c2a4dc332)
-- Skipping mood field to avoid constraint violations

INSERT INTO public.quotes (
  quote_text,
  author,
  book,
  chapter,
  page_number,
  source_url,
  is_favorite,
  is_public,
  view_count,
  share_count,
  difficulty_level,
  tags,
  user_id,
  author_id,
  category_id
) VALUES
  (
    'The only way to do great work is to love what you do. If you haven''t found it yet, keep looking. Don''t settle.',
    'Steve Jobs',
    'Stanford Commencement Address',
    NULL,
    NULL,
    'https://news.stanford.edu/2005/06/14/jobs-061505/',
    true,
    false,
    12,
    3,
    2,
    ARRAY['motivation', 'work', 'passion', 'success'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  ),
  (
    'In the end, we will remember not the words of our enemies, but the silence of our friends.',
    'Martin Luther King Jr.',
    'The Trumpet of Conscience',
    'Chapter 4',
    67,
    NULL,
    true,
    false,
    8,
    5,
    3,
    ARRAY['friendship', 'courage', 'justice', 'social'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  ),
  (
    'It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.',
    'Charles Darwin',
    'Origin of Species',
    'Chapter 15',
    234,
    NULL,
    false,
    false,
    15,
    7,
    4,
    ARRAY['evolution', 'adaptation', 'science', 'survival'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  ),
  (
    'The cave you fear to enter holds the treasure you seek.',
    'Joseph Campbell',
    'The Hero with a Thousand Faces',
    'Chapter 3',
    89,
    NULL,
    true,
    false,
    22,
    11,
    3,
    ARRAY['courage', 'fear', 'growth', 'mythology'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  ),
  (
    'Yesterday is history, tomorrow is a mystery, today is a gift. That is why it is called the present.',
    'Eleanor Roosevelt',
    'You Learn by Living',
    'Chapter 7',
    156,
    NULL,
    false,
    false,
    9,
    4,
    2,
    ARRAY['mindfulness', 'present', 'wisdom', 'time'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  ),
  (
    'Innovation distinguishes between a leader and a follower.',
    'Steve Jobs',
    'Fortune Magazine Interview',
    NULL,
    NULL,
    'https://fortune.com/2012/11/11/steve-jobs-innovation/',
    true,
    false,
    18,
    9,
    2,
    ARRAY['innovation', 'leadership', 'business', 'creativity'],
    '01928952-694d-7ac4-b454-ad9c2a4dc332',
    NULL,
    NULL
  );