// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxdpqubitozndqgaacbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4ZHBxdWJpdG96bmRxZ2FhY2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzQ2MjcsImV4cCI6MjA3MTc1MDYyN30.lsj6Wn2ox7F6ALBen3bgueQhGH21DzZt2L1l_h_TuoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});